name: flutter_bloc_course_vandad
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  image_picker: ^0.8.7
  meta: ^1.8.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

        
    
    
                                      